version: '3'

services:
  catalyst:
    build: './catalyst'
    image: 'catalyst:latest'

  mysql:
    image: 'mysql:5.7'
    volumes: 
      - 'catalogue_mysql:/var/lib/mysql'
      - './sql:/docker-entrypoint-initdb.d'
    env_file: 
      - '.env'
      - '.mysql_env'
    expose:
      - 3306

  app:
    build: './app'
    depends_on: 
      - 'catalyst'
    volumes:
      - './app/Catalogue:/usr/src/Catalogue'
    command: >
            perl script/catalogue_fastcgi.pl -l :3000 -n 5
    expose: 
      - 3000

  web:
    image: 'nginx:1.15.7-perl'
    depends_on: 
      - 'app'
    ports:
      - '80:80'
    volumes:
      - './etc:/etc/nginx/conf.d'

volumes:
  'catalogue_mysql': {}
